apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-analytics-app-deployment  # Name of your deployment
spec:
  replicas: 2  # Number of pods (instances) of your app to run
  selector:
    matchLabels:
      app: data-analytics-app
  template:
    metadata:
      labels:
        app: data-analytics-app
    spec:
      containers:
      - name: data-analytics-app  # Name of the container
        image: data-analytics-app  # Replace with your actual image name
        imagePullPolicy: Never
        ports:
        - containerPort: 5000  # Port the container exposes
